name: Build HeatSim (Windows)

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path .\requirements.txt) { pip install -r requirements.txt } else { pip install pyinstaller }

      - name: Build executable (PowerShell script)
        shell: pwsh
        run: |
          Write-Host 'Running build_exe.ps1'
          if (Test-Path .\build_exe.ps1) { .\build_exe.ps1 } else { Write-Host 'build_exe.ps1 not found, using pyinstaller via spec if present'; if (Test-Path .\HeatSim.spec) { pyinstaller .\HeatSim.spec } else { pyinstaller --onefile main.py -n HeatSim } }

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: HeatSim-windows-exe
          path: dist/HeatSim.exe
